package client;

import messages.Message;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.function.Consumer;

public class Authorize {
    public Authorize(Consumer<Authorize> confirmListener) {
        confirmButton.addActionListener((action) -> confirmListener.accept(this));
    }

    public synchronized JTextField getName() {
        return textField1;
    }

    public synchronized JTextField getAddress() {
        return textField2;
    }

    public Container getContentPane() {
        return MainPanel;
    }

    public JLabel getErrorLabel() {
        return ErrorLabel;
    }

    private JPanel MainPanel;
    private JTextField textField1;
    private JButton confirmButton;
    private JTextField textField2;
    private JLabel ErrorLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        MainPanel.add(panel1, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Your name: ");
        panel1.add(label1);
        textField1 = new JTextField();
        textField1.setColumns(20);
        panel1.add(textField1);
        confirmButton = new JButton();
        confirmButton.setText("Confirm");
        panel1.add(confirmButton);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        MainPanel.add(panel2, BorderLayout.NORTH);
        final JLabel label2 = new JLabel();
        label2.setText("IP:port");
        panel2.add(label2);
        textField2 = new JTextField();
        textField2.setColumns(20);
        panel2.add(textField2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        MainPanel.add(panel3, BorderLayout.SOUTH);
        ErrorLabel = new JLabel();
        ErrorLabel.setForeground(new Color(-6094080));
        ErrorLabel.setText("");
        panel3.add(ErrorLabel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
